MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using MvcOnlineTicariOtomasyon.Models.Sınıflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class SatisController : Controller
    {
        // GET: Satis
        Context context = new Context();

        public ActionResult Index()
        {
            var satislar = context.SatisHarekets.ToList();
            return View(satislar);
        }

        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> urunList = (from x in context.Uruns.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.UrunAd,
                                                 Value = x.Urunid.ToString()
                                             }).ToList();
            ViewBag.UrunList = urunList;

            List<SelectListItem> cariList = (from x in context.Carilers.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.CariAd + " " + x.CariSoyad,
                                                 Value = x.Cariid.ToString()
                                             }).ToList();
            ViewBag.CariList = cariList;

            List<SelectListItem> personelList = (from x in context.Personels.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.PersonelAd + " " + x.PersonelSoyad,
                                                     Value = x.Personelid.ToString()
                                                 }).ToList();
            ViewBag.PersonelList = personelList;

            return View();
        }

        [HttpPost]
        public ActionResult YeniSatis(SatisHareket satisHareket)
        {
            satisHareket.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            context.SatisHarekets.Add(satisHareket);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> urunList = (from x in context.Uruns.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.UrunAd,
                                                 Value = x.Urunid.ToString()
                                             }).ToList();
            ViewBag.UrunList = urunList;

            List<SelectListItem> cariList = (from x in context.Carilers.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = x.CariAd + " " + x.CariSoyad,
                                                 Value = x.Cariid.ToString()
                                             }).ToList();
            ViewBag.CariList = cariList;

            List<SelectListItem> personelList = (from x in context.Personels.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = x.PersonelAd + " " + x.PersonelSoyad,
                                                     Value = x.Personelid.ToString()
                                                 }).ToList();
            ViewBag.PersonelList = personelList;

            var satis = context.SatisHarekets.Find(id);
            return View("SatisGetir", satis);
        }

        public ActionResult SatisGuncelle(SatisHareket satisHareket)
        {
            var Satis = context.SatisHarekets.Find(satisHareket.Satisid);
            Satis.Cariid = satisHareket.Cariid;
            Satis.Adet = satisHareket.Adet;
            Satis.Fiyat = satisHareket.Fiyat;
            Satis.Personelid = satisHareket.Personelid;
            Satis.Tarih = DateTime.Now;
            Satis.ToplamTutar = satisHareket.ToplamTutar;
            Satis.Urunid = satisHareket.Urunid;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult SatisDetay(int id)
        {
            var values = context.SatisHarekets.Where(x => x.Satisid == id).ToList();
            return View(values);
        }

        public ActionResult UrunListesi()
        {
            var values = context.Uruns.ToList();
            return View(values);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Sınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<a href="/Satis/YeniSatis" class="btn btn-primary">Yeni Satış Yap</a>
<br />
<br />

<table id="tbl1" class="table table-striped">
    <thead>
        <tr>
            <th>Satış ID</th>
            <th>Ürün</th>
            <th>Cari</th>
            <th>Personel</th>
            <th>Adet</th>
            <th>Fiyat</th>
            <th>Toplam Tutar</th>
            <th>Tarih</th>
            <th>İşlemler</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Satisid</td>
            <td>@item.Urun.UrunAd</td>
            <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
            <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
            <td>@item.Adet</td>
            <td>@item.Fiyat</td>
            <td>@item.ToplamTutar</td>
            <td>@item.Tarih.ToString("dd.MM.yyyy")</td>
            <td>
                <a href="/Satis/SatisDetay/@item.Satisid" class="btn btn-success">Detaylar</a>
                <a href="/Satis/SatisGetir/@item.Satisid" class="btn btn-warning">Güncelle</a>
            </td>
        </tr>
    }
</table>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>
<script>
    $('#tbl1').dataTable({});
</script>

MvcOnlineTicariOtomasyon/Views/Satis/SatisDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Sınıflar
@model List<SatisHareket>
@{
    ViewBag.Title = "SatisDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış Detayı</h2>
<br />
<button href></button>
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Satisid</td>
            <td>@item.Urun.UrunAd</td>
            <td>@item.Cariler.CariAd @item.Cariler.CariSoyad</td>
            <td>@item.Personel.PersonelAd @item.Personel.PersonelSoyad</td>
            <td>@item.Fiyat</td>
            <td>@item.Adet</td>
            <td>@item.ToplamTutar</td>
            <td>@item.Tarih.ToString("dd.MM.yyyy")</td>
        </tr>
    }
</table>
<button class="btn btn-default" style="background-color:dodgerblue">Yazdır</button>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Satış İşlemi Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.Satisid)
        @Html.LabelFor(x => x.Urun)
        @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.UrunList, new { @class = "form-control" })
        <br />
        @Html.Label("Cari")
        @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.CariList, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Personel)
        @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.PersonelList, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Adet)
        @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Fiyat)
        @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.ToplamTutar)
        @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Tarih)
        @Html.TextBoxFor(x => x.Tarih, new { @class = "form-control", @readonly = "readonly" })
    </div>
    <button class="btn btn-warning">Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Sınıflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Satış Sayfası</h2>
<br />
<form method="post" class="form-group">
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x => x.Urunid, (List<SelectListItem>)ViewBag.UrunList, new { @class = "form-control" })
    <br />
    @Html.Label("Cari")
    @Html.DropDownListFor(x => x.Cariid, (List<SelectListItem>)ViewBag.CariList, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.PersonelList, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    @Html.TextBoxFor(x => x.Adet, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    @Html.TextBoxFor(x => x.ToplamTutar, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Satış Yap</button>
</form>