MvcOnlineTicariOtomasyon/Models/Sınıflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Sınıflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipId { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(10)]
        public string TakipKodu { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(100)]
        public string Aciklama { get; set; }
        public DateTime TarihZaman { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using MvcOnlineTicariOtomasyon.Models.Sınıflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        Context context = new Context();
        public ActionResult Index(string p)
        {
            var k = from x in context.KargoDetays select x;
            if (!string.IsNullOrEmpty(p))
            {
                k = k.Where(y => y.TakipKodu.Contains(p));
            }

            return View(k.ToList());
        }

        [HttpGet]
        public ActionResult YeniKargo()
        {

            Random rnd = new Random();
            string[] karakterler = { "A", "B", "C", "D", "E", "F", "G", "H", "K" };
            int k1, k2, k3;
            k1 = rnd.Next(0, karakterler.Length);
            k2 = rnd.Next(0, karakterler.Length);
            k3 = rnd.Next(0, karakterler.Length);
            int s1, s2, s3;
            s1 = rnd.Next(100, 1000);
            s2 = rnd.Next(10, 99);
            s3 = rnd.Next(10, 99);
            string kod = s1.ToString() + karakterler[k1] + s2 + karakterler[k2] + s3 + karakterler[k3];
            ViewBag.TakipKodu = kod;

            return View();
        }

        [HttpPost]
        public ActionResult YeniKargo(KargoDetay kargoDetay)
        {
            context.KargoDetays.Add(kargoDetay);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KargoTakip(string id)
        {
            var degerler = context.KargoTakips.Where(x => x.TakipKodu == id).ToList();

            return View(degerler);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Sınıflar
@model List<KargoDetay>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="container-fluid">
    <br />
    <a href="/Kargo/YeniKargo" class="btn btn-primary">Yeni Kargo Girişi</a>
    <br />
    <br />
    @using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
    {
        <p>
            Kargo Takip Kodu: @Html.TextBox("p")
            <input type="submit" value="Ara" />
        </p>
    }
    <br />
    <table class="table table-bordered">
        <tr>
            <th>Personel</th>
            <th>Alıcı</th>
            <th>Tarih</th>
            <th>Kargo Takip Kodu</th>
            <th>İşlemler</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Personel</td>
                <td>@item.Alici</td>
                <td>@item.Tarih</td>
                <td>@item.TakipKodu</td>
                <td>
                    <a href="/Kargo/KargoTakip/@item.TakipKodu" class="btn btn-success">Detaylar</a>
                </td>
            </tr>
        }
    </table>
</div>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Sınıflar
@model List<KargoTakip>

@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<table class="table table-striped">
    <tr>
        <th>Açıklama</th>
        <th>Tarih</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Aciklama</td>
            <td>@item.TarihZaman</td>
        </tr>
    }
</table>

MvcOnlineTicariOtomasyon/Views/Kargo/YeniKargo.cshtml
@model MvcOnlineTicariOtomasyon.Models.Sınıflar.KargoDetay
@{
    ViewBag.Title = "YeniKargo";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Yeni Kargo Bilgi Sayfası</h2>
<br />
<form method="post" class="form-group">
    @Html.LabelFor(x => x.TakipKodu)
    <input type="text" value="@ViewBag.TakipKodu" class="form-control" name="TakipKodu" readonly />
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.TextBoxFor(x => x.Personel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Alici)
    @Html.TextBoxFor(x => x.Alici, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    <input class="form-control" type="date" name="Tarih" />
    <br />
    @Html.LabelFor(x => x.Aciklama)
    @Html.TextAreaFor(x => x.Aciklama, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>